# Generated by Django 4.1.6 on 2023-03-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdudent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_1', models.IntegerField(max_length=10)),
                ('assignment_2', models.IntegerField(max_length=10)),
                ('assignment_3', models.IntegerField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdudent.student')),
            ],
        ),
    ]
