# Generated by Django 4.1.6 on 2023-05-04 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdudent', '0002_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='assignment_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='assignment_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='assignment_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=255, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gpa',
            field=models.FloatField(verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='Student ID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
